import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: '#f8f7ff' },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 20,
    backgroundColor: '#fff',
  },
  headerTitle: { fontSize: 20, fontWeight: 'bold', color: '#333' },
  tabsContainer: {
    flexDirection: 'row',
    padding: 15,
    justifyContent: 'space-around',
  },
  tab: {
    paddingVertical: 8,
    paddingHorizontal: 20,
    borderRadius: 20,
    backgroundColor: '#e6e6fa',
  },
  activeTab: { backgroundColor: '#8A2BE2' },
  tabText: { color: '#555', fontWeight: '600' },
  activeTabText: { color: '#fff' },
  listContent: { padding: 20, paddingBottom: 80 },
  taskCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    padding: 15,
    borderRadius: 12,
    marginBottom: 15,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  checkboxContainer: { marginRight: 15 },
  taskInfo: { flex: 1 },
  taskTitle: { fontSize: 16, color: '#333', fontWeight: '500' },
  completedText: { textDecorationLine: 'line-through', color: '#aaa' },
  metaRow: { flexDirection: 'row', alignItems: 'center', marginTop: 5 },
  dateText: { fontSize: 12, color: '#888' },
  overdueText: { color: '#FF5252', fontWeight: 'bold' },
  deleteButton: { padding: 5 },
  fab: {
    position: 'absolute',
    right: 20,
    bottom: 30,
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: '#8A2BE2',
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 5,
  },
  emptyState: { alignItems: 'center', marginTop: 50 },
  emptyText: { color: '#999', marginTop: 10, fontSize: 16 },
});

export default styles;